id: I967DA727
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-18T05:40:48+00:00'
last_modified: '2022-06-08T04:09:30.000424+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD107937
  title: གསུང་འབུམ། ངག་དབང་བློ་བཟང་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D40C:
      image_group_id: I1PD107939
      title: Volume 1 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 632
      order: 1
      base_file: D40C.txt
    B7AD:
      image_group_id: I1PD107940
      title: Volume 2 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 574
      order: 2
      base_file: B7AD.txt
    '0706':
      image_group_id: I1PD107941
      title: Volume 3 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 566
      order: 3
      base_file: 0706.txt
    ACED:
      image_group_id: I1PD107942
      title: Volume 4 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 578
      order: 4
      base_file: ACED.txt
    AAAA:
      image_group_id: I1PD107943
      title: Volume 5 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 566
      order: 5
      base_file: AAAA.txt
    F69F:
      image_group_id: I1PD107944
      title: Volume 6 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 420
      order: 6
      base_file: F69F.txt
    8E0F:
      image_group_id: I1PD107945
      title: Volume 7 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 370
      order: 7
      base_file: 8E0F.txt
    7FFE:
      image_group_id: I1PD107946
      title: Volume 8 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 590
      order: 8
      base_file: 7FFE.txt
    E515:
      image_group_id: I1PD107947
      title: Volume 9 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 478
      order: 9
      base_file: E515.txt
    1C8F:
      image_group_id: I1PD107948
      title: Volume 10 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 548
      order: 10
      base_file: 1C8F.txt
    E999:
      image_group_id: I1PD107949
      title: Volume 11 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 596
      order: 11
      base_file: E999.txt
    BCBE:
      image_group_id: I1PD107950
      title: Volume 12 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 620
      order: 12
      base_file: BCBE.txt
    7DA8:
      image_group_id: I1PD107951
      title: Volume 13 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 542
      order: 13
      base_file: 7DA8.txt
    1A14:
      image_group_id: I1PD107952
      title: Volume 14 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 538
      order: 14
      base_file: 1A14.txt
    C7B9:
      image_group_id: I1PD107953
      title: Volume 15 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 628
      order: 15
      base_file: C7B9.txt
    '2426':
      image_group_id: I1PD107954
      title: Volume 16 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 578
      order: 16
      base_file: 2426.txt
    B636:
      image_group_id: I1PD107955
      title: Volume 17 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 694
      order: 17
      base_file: B636.txt
    A83A:
      image_group_id: I1PD107956
      title: Volume 18 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 500
      order: 18
      base_file: A83A.txt
    58D6:
      image_group_id: I1PD107957
      title: Volume 19 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 404
      order: 19
      base_file: 58D6.txt
    48DB:
      image_group_id: I1PD107958
      title: Volume 20 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 414
      order: 20
      base_file: 48DB.txt
    '3587':
      image_group_id: I1PD107959
      title: Volume 21 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 486
      order: 21
      base_file: 3587.txt
    6AA0:
      image_group_id: I1PD107960
      title: Volume 22 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 638
      order: 22
      base_file: 6AA0.txt
    828A:
      image_group_id: I1PD107961
      title: Volume 23 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 514
      order: 23
      base_file: 828A.txt
    '9399':
      image_group_id: I1PD107962
      title: Volume 24 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 598
      order: 24
      base_file: 9399.txt
    A15C:
      image_group_id: I1PD107963
      title: Volume 25 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 630
      order: 25
      base_file: A15C.txt
    89FE:
      image_group_id: I1PD107964
      title: Volume 26 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 634
      order: 26
      base_file: 89FE.txt
    474A:
      image_group_id: I1PD107965
      title: Volume 27 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 630
      order: 27
      base_file: 474A.txt
    47DA:
      image_group_id: I1PD107966
      title: Volume 28 of gsung 'bum/_ngag dbang blo bzang rgya mtsho/
      total_pages: 524
      order: 28
      base_file: 47DA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
